package com.example.codingagent.logging;

public enum EventType {
    TASK_RECEIVED,
    REPOSITORY_SCANNED,
    FILE_READ,
    SEARCH_PERFORMED,
    PLAN_CREATED,
    MODEL_REQUEST,
    MODEL_RESPONSE,
    FILE_MODIFIED,
    COMMAND_EXECUTED,
    TEST_STARTED,
    TEST_FAILED,
    RECOVERY_STARTED,
    RECOVERY_ATTEMPT,
    TEST_PASSED,
    VERIFICATION_STARTED,
    TASK_COMPLETED,
    TASK_FAILED,
    TASK_CANCELLED,
    ERROR
}
